baseURL = "https://synacklabs.github.io/"
languageCode = "es-es"
defaultContentLanguage = "es"
theme = "re-terminal"
pagination.pagerSize = 5

[params]
  # Carpeta donde guarda el script los posts (NO CAMBIAR)
  contentTypeName = "posts"

  # Colores disponibles: ["orange", "blue", "red", "green", "pink", "paper"]
  # "green" queda muy hacker, "pink" o "red" para red team, "blue" para blue team.
  themeColor = "pink"

  # Mostrar menú
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true 
  autoCover = true
  showLastUpdated = true

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
    
    [languages.es.params]
      title = "SynAckLabs"
      subtitle = "| Red Team & Blue Team"
      owner = "SynAckLabs"
      keywords = "cybersecurity, hacking, red team, blue team, ciberseguridad"
      copyright = "SynAckLabs"
      
      # Traducciones al español de la interfaz
      menuMore = "Ver más"
      readMore = "Leer más..."
      readOtherPosts = "Otros logs"
      newerPosts = "Logs recientes"
      olderPosts = "Logs antiguos"
      missingContentMessage = "404: not found..."
      missingBackButtonLabel = "Volver a localhost"
      minuteReadingTime = "min lectura"
      words = "palabras"

    [languages.es.params.logo]
      # Esto es lo que sale arriba a la izquierda. El :~# simula ser root
      logoText = "root@SynAckLabs:~#" 
      logoHomeLink = "/"

    [languages.es.menu]
      # 1. El About
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Whoweare"
        url = "/about"
        weight = 1
      
      # 2. SECCIÓN FILTROS (Nuevas)
      [[languages.es.menu.main]]
        identifier = "machines"
        name = "/var/machines"   # Solo Máquinas
        url = "/categories/machine"
        weight = 2

      [[languages.es.menu.main]]
        identifier = "challenges"
        name = "/var/challenges" # Solo Challenges
        url = "/categories/challenge"
        weight = 3

      # 3. SECCIÓN "VER TODO" 
      [[languages.es.menu.main]]
        identifier = "posts"
        name = "/var/all_logs"   
        url = "/posts"
        weight = 4
      [[languages.es.menu.main]]
        identifier = "search"
        name = "grep"
        url = "/search"
        weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]